b = bytearray(b"  AbC  ")
print(b.strip())
print(type(b.strip()))
print(b.lower())
print(type(b.lower()))
print(b.upper())
print(b.capitalize())
print(b.swapcase())
print(bytearray(b"hello world").title())
