b = bytearray(b"abc")
print(b)
print(len(b))
b[1] = 90
print(b)
b.append(33)
b.extend([1, 2])
print(b)
print(list(b))
print(b[1:4])
print(b + bytearray(b"Q"))
print(bytearray(b"x") * 3)
print(type(b))
print(isinstance(b, bytearray))
