b = bytearray(b"ab--cd--ef")
print(b.find(b"--"))
print(b.count(b"-"))
print(b.startswith(b"ab"))
print(b.endswith(b"ef"))
print(b.replace(b"--", b":"))
print(type(b.replace(b"--", b":")))
print(b.split(b"--"))
print(bytearray(b",").join([bytearray(b"a"), b"b"]))
